### ISSUE TITLE
Proposal Question

### ISSUE THREAD

**Issue by aylapear** [UBC-MDS/DSCI_522_payla_rzitomer#3]
This is what i asked Mike: 
I have a question about creating a good predictive question. We want to use a database about wine for a machine learning model. The dataset has parameters like price, region, variety, and ranks flavor of the wine. This is the question we have drafted: Can we use decision trees to predict if a wine has a WineEnthusiast rating above 90 points based on country, price, province, region, variety and winery?

-    I am wondering if we should list the parameters in the question?
-    Would  the question be clearer if we put something in about an accuracy threshold: Can we use decision trees to predict if a wine has a WineEnthusiast rating above 90 points based on country, price, province, region, variety and winery with a model accuracy greater than 90%?

Here is Mike's response: 
I think that question makes sense. I think it’s sensible to list the parameters and definitely a good idea to list the desired accuracy.

**Comment by rzitomer** [comment]
I agree, 90% sounds reasonable. We could also base our question on what Tiffany said here: "If you are interested in know the top N predictors from a decision tree (because that is the predictive question you are asking), in scikit-learn you can access a score for each feature through the feature_importances_ field after fitting, and then grab the top 3." 

So we could change our question to be something like: "Can we use decision trees to predict the top 3 predictors that a wine will get a WineEnthusiast rating above 90 points?"

We could also just add the accuracy score so our question would be: "Can we use decision trees to predict if a wine has a WineEnthusiast rating above 90 points based on country, price, province, region, variety and winery with at least 90% accuracy?" (this is literally just the question we had plus the accuracy).

I think either works well.

**Comment by aylapear** [comment]
I like all the suggestions from this issue and the wine ratings issue. I will incorporate a few options into the proposal and then you can edit it and select one. While I'm incorporating them I will think about if I have a preference for one of them over the others, I think they are all good ideas.

**Comment by rzitomer** [comment]
They're all good. I'd vote number 1, like you said, it seems the most useful

**Comment by rzitomer** [comment]
Looking at the data further, I'm afraid it would make more sense to categorize whether or not a wine was rated as having >=90 points as opposed to whether or not a wine has >= 98 points. There are very few (129 rows before any filtering; which is <.01% of rows) rows that are >=98 points, whereas there are much more rows (49045 rows before any filtering, ~38% of rows) that are >= 90 points. 

If we want to stick with predicting >=98, we might have to think about dealing with unbalanced data (https://stats.stackexchange.com/questions/28029/training-a-decision-tree-against-unbalanced-data). 

I personally think it would be better to change our question, but obviously happy to discuss further. We can also discuss with Eric and Tiffany tomorrow.
